[project]
name = "ai-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Deekshithavarma", email = "deekshithavarma828@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
ai-template = "ai_template:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "ruff>=0.16.10",
]
